### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by NorseGaud**

### CODE REVIEW

**Review by casperklein — APPROVED** [review]

**Comment by NorseGaud** [comment]
@wernerfred how do we want to do write access for this repo?

**Comment by wernerfred** [comment]
Sorry i am only available in mobile right now, what is the Problem?

**Review by wernerfred — DISMISSED** [review]

**Comment by wernerfred** [comment]
Ah i found that docker-mailservers maintainers were only granted triage rights in this repo. Fixed it with write currently (therefore casperkleins Review now counts) but i will rebuild the Teams and permission System to be Independent for this repo once i am on a Desktop PC again. 

So currently a PR needs at least one Review From someone with write Access (which are currently docker-mailserver maintainers + you and lukemarlin)

**Comment by NorseGaud** [comment]
Thanks for taking a look! That was what I was curious about :)

**Comment by thehunt100** [comment]
Is there a roadmap for this?

**Comment by NorseGaud** [comment]
@thehunt100 no. Please feel free to help contribute to the project to speed it up.

**Comment by thehunt100** [comment]
I just noticed this thread https://github.com/docker-mailserver/docker-mailserver-admin/issues/3. I will reply there.

**Pull request merged**
